# Generated by Django 6.0.3 on 2026-03-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
