# Generated by Django 6.0.3 on 2026-03-25 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_incident_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera_Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.camera')),
            ],
        ),
    ]
