# Generated by Django 6.0.3 on 2026-03-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_camera_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera_incident',
            name='footage',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
