# Generated by Django 6.0.3 on 2026-03-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_camera_incident_footage'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='live',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
